# Generated by Django 4.0.5 on 2022-09-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=20)),
                ('group', models.CharField(max_length=20)),
                ('question_num', models.IntegerField()),
                ('text', models.CharField(max_length=250)),
                ('answerA', models.CharField(max_length=150)),
                ('answerB', models.CharField(max_length=150)),
                ('answerC', models.CharField(max_length=150)),
                ('answerD', models.CharField(max_length=150)),
                ('duration', models.IntegerField()),
                ('startTime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
