# Generated by Django 4.0.5 on 2022-09-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correctAns',
            field=models.CharField(default='X', max_length=1),
            preserve_default=False,
        ),
    ]
