# Generated by Django 4.0.5 on 2022-07-16 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myChannels', '0002_rename_channel_layer_active_channel_channel_nane'),
    ]

    operations = [
        migrations.RenameField(
            model_name='active_channel',
            old_name='channel_nane',
            new_name='channel_name',
        ),
    ]
