# Generated by Django 4.0.5 on 2022-07-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myChannels', '0004_active_channel_quiz_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='active_channel',
            name='lastSeen',
            field=models.DateTimeField(default='2021-12-31 15:25:00'),
            preserve_default=False,
        ),
    ]
