# Generated by Django 4.0.5 on 2022-10-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myChannels', '0005_active_channel_lastseen'),
    ]

    operations = [
        migrations.AddField(
            model_name='active_channel',
            name='userID',
            field=models.IntegerField(default=99),
            preserve_default=False,
        ),
    ]
