# Generated by Django 4.0.5 on 2022-10-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizusr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin User'), ('Quizmaster', 'Quizmaster'), ('StdUser', 'Standard User'), ('Guest', 'Guest')], default='StdUser', max_length=20),
        ),
    ]
